# https://github.com/googleapis/repo-automation-bots/tree/main/packages/release-please#configuration
handleGHRelease: true
releaseType: simple
extraFiles:
  - components/adaptive_lighting/adaptive_lighting_version.h
