substitutions:
  devicename: cwww-light

esphome:
  name: "${devicename}"

external_components:
  - source: github://mdvorak/esphome-components

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
captive_portal:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${devicename}-AP"

adaptive_lightning:
  - light_id: cwww_light
    name: "Adaptive Lightning"

output:
  - platform: ledc
    id: ledc_cold
    pin: 21
  - platform: ledc
    id: ledc_warm
    pin: 22

light:
  - platform: cwww
    id: cwww_light
    name: "Light"
    cold_white: ledc_cold
    warm_white: ledc_warm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K

sun:
  latitude: 48.8584°
  longitude: 2.2945°

time:
  - platform: sntp
