substitutions:
  devicename: adaptive-light

esphome:
  name: "${devicename}"
  min_version: 2025.6.0

external_components:
  - source: ./components

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

wifi:
  ssid: TEST
  password: testtest
  ap:
    ssid: "${devicename}-AP"

adaptive_lighting:
  - light_id: cwww_light
    name: "Adaptive Lighting"

output:
  - platform: ledc
    id: ledc_cold
    pin: 21
  - platform: ledc
    id: ledc_warm
    pin: 22

light:
  - platform: cwww
    id: cwww_light
    name: "Light"
    cold_white: ledc_cold
    warm_white: ledc_warm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true

sun:
  latitude: 48.8584°
  longitude: 2.2945°

time:
  - platform: sntp
